import { CategoryType, RegistryItem } from './types';

export const FRAMEWORKS: RegistryItem[] = [
  { id: 'f1', name: 'R.A.C.E.', description: 'Role, Action, Context, Expectation. The foundational structural standard.', category: CategoryType.FRAMEWORK, group: 'Core' },
  { id: 'f2', name: 'C.O.T.', description: 'Chain-of-Thought. Forcing step-by-step reasoning.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f3', name: 'ToT', description: 'Tree-of-Thought. Multi-path divergent exploration.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f4', name: 'Few-Shot', description: 'Voice Cloning via high-quality examples.', category: CategoryType.FRAMEWORK, group: 'Style' },
  { id: 'f5', name: 'Reverse Prompting', description: 'Extracting DNA from masterworks.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f6', name: 'Socratic Interview', description: 'AI interviews user before drafting.', category: CategoryType.FRAMEWORK, group: 'Interactive' },
  { id: 'f7', name: 'CRISPE', description: 'Capacity, Role, Insight, Statement, Polish, Executive.', category: CategoryType.FRAMEWORK, group: 'Core' },
  { id: 'f8', name: 'D.F.C.', description: 'Delimiter-Focused Command (###). Structural isolation.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f9', name: 'Negative Prompting', description: 'Defining "Off-Limit" zones to avoid cliches.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f10', name: 'Simulation Pattern', description: 'Stress-testing via Skeptical Peer persona.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f11', name: 'R.G.C.', description: 'Role, Goal, Constraints. High-speed precision.', category: CategoryType.FRAMEWORK, group: 'Core' },
  { id: 'f12', name: 'Chain-of-Verification', description: 'Verify facts before final output.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f13', name: 'Step-Back Prompting', description: 'Abstract principles before solutions.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f14', name: 'Analogical Logic', description: 'Solving using cross-domain parallels.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f15', name: 'First-Principles', description: 'Deconstruct to foundational truths.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f16', name: 'Recursive Synth', description: 'Iterative summarization for density.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f17', name: 'Inversion Principle', description: 'Solving by avoiding negative outcomes.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f18', name: 'Delimiter Stacking', description: 'Using nested structural markers.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f19', name: 'Context Injection', description: 'Saturating context window with data.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f20', name: 'Role-Anchor', description: 'Deep behavioral persistence.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f21', name: 'Least-to-Most', description: 'Minimal solvable unit decomposition.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f22', name: 'Self-Consistency', description: 'Multi-path majority vote logic.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f23', name: 'ReAct Pattern', description: 'Thought-Action-Observation loops.', category: CategoryType.FRAMEWORK, group: 'Interactive' },
  { id: 'f24', name: 'Meta-Prompting', description: 'AI self-optimization protocol.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f25', name: 'Chain-of-Density', description: 'Iterative info-compression.', category: CategoryType.FRAMEWORK, group: 'Style' },
  { id: 'f26', name: 'Zero-Shot CoT', description: 'Implicit reasoning triggers.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f27', name: 'Emotional Stimuli', description: 'Urgency-based priority shifting.', category: CategoryType.FRAMEWORK, group: 'Style' },
  { id: 'f28', name: 'Progressive Refinement', description: 'Iterative drafting with critique.', category: CategoryType.FRAMEWORK, group: 'Interactive' },
  { id: 'f29', name: 'Contrastive Prompting', description: 'Do vs Don\'t boundary setting.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f30', name: 'PAL Structure', description: 'Program-Aided Language logic.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f31', name: 'Perspective Stacking', description: 'Multi-lensed problem solving.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f32', name: 'Info-Gap Lock', description: 'Identify unknowns before starting.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f33', name: 'Fallacy Filter', description: 'Cognitive bias detection.', category: CategoryType.FRAMEWORK, group: 'Logic' },
  { id: 'f34', name: 'Cross-Domain Sync', description: 'Interdisciplinary logic transfer.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f35', name: 'Tone Scaffolding', description: 'Layered stylistic building.', category: CategoryType.FRAMEWORK, group: 'Style' },
  { id: 'f36', name: 'Constraint Stacking', description: 'Hyper-precise multi-constraint forcing.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f37', name: 'Dynamic Formatting', description: 'Self-adapting output schema.', category: CategoryType.FRAMEWORK, group: 'Core' },
  { id: 'f38', name: 'Knowledge Retrieval', description: 'Search-before-synthesis protocol.', category: CategoryType.FRAMEWORK, group: 'Interactive' },
  { id: 'f39', name: 'Bias Mitigation', description: 'Explicit viewpoint neutrality.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f40', name: 'Format Enforcement', description: 'Rigid structural validation.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f41', name: 'Instruction Anchor', description: 'Goal repetition at EOF.', category: CategoryType.FRAMEWORK, group: 'Control' },
  { id: 'f42', name: 'Variable Assignment', description: 'Abstract term definition for logic.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f43', name: 'Prompt Chaining', description: 'Sequential logic dependencies.', category: CategoryType.FRAMEWORK, group: 'Interactive' },
  { id: 'f44', name: 'System Priming', description: 'Architectural rule initialization.', category: CategoryType.FRAMEWORK, group: 'Core' },
  { id: 'f45', name: 'Multi-Modal Fusion', description: 'Visual-Logic-Text synthesis.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f46', name: 'Recursive Prompting', description: 'Self-improving instruction sets.', category: CategoryType.FRAMEWORK, group: 'Advanced' },
  { id: 'f47', name: 'Few-Shot Seeding', description: 'Format anchoring via examples.', category: CategoryType.FRAMEWORK, group: 'Style' },
  { id: 'f48', name: 'Role-Play Constraints', description: 'Strict behavioral simulation.', category: CategoryType.FRAMEWORK, group: 'Style' },
  { id: 'f49', name: 'Metric-Tuning', description: 'Exact success criteria definition.', category: CategoryType.FRAMEWORK, group: 'Core' },
  { id: 'f50', name: 'Final Logic Seal', description: 'Pre-transmission verification.', category: CategoryType.FRAMEWORK, group: 'Control' }
];
